version: '3.7'

services:
  backend:
      container_name: backend
      build: 
        context: ./server
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      command: npm run dev
  
  frontend:
    container_name: frontend
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080