version: "3.9"
services:
  backend:
    image: "rawdagastan/calculator:server"
    ports:
      - "3000:3000"

  frontend:
    environment:
      - VUE_APP_BACKEND="https://localhost:3010/"
    image: "rawdagastan/calculator:client"
    ports:
      - "8085:8085"

  svelte:
    image: "rawdagastan/calculator:svelte_client"
    ports:
      - "8080:8080"