
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30081
  selector:
    app: server
    tier: backend
  type: NodePort
status:
  loadBalancer: {}