apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
spec:
  selector:
    matchLabels:
      app: server
      tier: backend
  template:
    metadata:
      name: server-podd
      labels:
        app: server
        tier: backend
    spec:
      containers:
      - name: server
        image: rawdagastan/calculator:server
        imagePullPolicy: Always
        env:
        - name: FRONTEND
          value: {{ .Values.frontend }}