apiVersion: apps/v1
kind: Deployment
metadata:
  name: svelte-deploy
spec:
  selector:
    matchLabels:
      app: svelte
      tier: frontend
  template:
    metadata:
      name: svelte-podd
      labels:
        app: svelte
        tier: frontend
    spec:
      containers:
      - name: svelte
        image: rawdagastan/calculator:svelte_client
        imagePullPolicy: Always
        env:
        - name: SVELTE_APP_BACKEND
          value: {{ .Values.backend }}
