apiVersion: v1
kind: Service
metadata:
  name: svelte-serv
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: svelte
    tier: frontend
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
